pipeline:
  deploy-1:
    image: appleboy/drone-ssh
    host: 11.1.11.174
    userrrname: vibrobox-deploy
    port: 34777
    secrets: [ ssh_key ]
    command_timeout: 100
    script:
      - set -e
      - cd /home/vibrobox/www/skf.vibrobox.com
    when:
      event: [ push ]

  notify-email:
    image: drillster/drone-email
    secrets: [ email_username, email_password ]
    host: smtp.gmail.com
    port: 587
    from: drone@vibrobox.com
    when:
      status: [ failure ]
      event: [ push ]

services:
  testdb:
    image: mariadb:10.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

 MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test